# =====================
# BASICO
# =====================

set -g prefix C-a
unbind C-b
bind C-a send-prefix

set -g mouse on
set -g history-limit 50000

#unicode
set -g default-terminal "screen-256color"
set -as terminal-overrides ",xterm-kitty:RGB"
set -ga terminal-overrides ",xterm-kitty:Tc"

# recargar config
bind r source-file ~/.config/tmux/tmux.conf \; display "tmux reloaded"

# dividir paneles estilo vim
bind | split-window -h
bind - split-window -v

bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# =====================
# STATUS BAR
# =====================

set -g status-position bottom
set -g status-interval 2

# =====================
# PLUGINS
# =====================

set -g @plugin 'tmux-plugins/tpm'

# CPU RAM
set -g @plugin 'tmux-plugins/tmux-cpu'

# Catppuccin theme
set -g @plugin 'catppuccin/tmux'

# Git info
set -g @plugin 'tmux-plugins/tmux-battery'

# ventanas bonitas
set -g @plugin 'tmux-plugins/tmux-sensible'

# =====================
# CATPPUCCIN CONFIG
# =====================

set -g @catppuccin_flavour 'mocha'

set -g @catppuccin_window_status_style "rounded"
set -g @catppuccin_window_left_separator "█"
set -g @catppuccin_window_right_separator "█"

set -g @catppuccin_status_left_separator ""
set -g @catppuccin_status_right_separator ""

set -g @catppuccin_status_modules_right "cpu battery date_time"
set -g @catppuccin_status_modules_left "session"

set -g @catppuccin_date_time_text "%H:%M"

# =====================
# TPM INIT
# =====================

run '~/.tmux/plugins/tpm/tpm'
